---
- name: Apt update
  apt:
    update_cache: yes

- name: Uninstall old versions
  apt:
    state: absent
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install docker dependencies
  apt:
    state: present
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add an Apt signing key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Apt update
  apt:
    update_cache: yes

- name: Install docker
  apt:
    state: present
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

# - name: Start service docker
#   service:
#       name: docker
#       state: restarted
